server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimalss22@gmail.com
    password: mwtjqsmcfcgufchd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    # url: jdbc:h2:mem:test;MODE=MySQL
    # driver-class-name: org.h2.Driver
    # username: sa
    # password: 
    url: jdbc:mysql://job-mysql-db.cqqtjqwrzdtq.ap-northeast-2.rds.amazonaws.com:3306/job?characterEncoding=utf-8&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: green123

    
  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
      data-locations:
      - classpath:db/data.sql
  # h2:
  #   console:
  #     enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
mybatis:
  mapper-locations:
  - mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
